### ISSUE TITLE
All url() in markitup*.css should use image_path helper

### ISSUE THREAD

**Issue by antage** [phlipper/markitup-rails#1]
This code

``` css
background-image:url(images/bg-editor-bbcode.png);
```

should be

``` css
background-image:url(<%= image_path "bg-editor-bbcode.png" %>);
```

All *.css should be renamed to *.css.erb.

Only `image_path` (or `asset_path`) can calculate absolute path with digest hash.

**Comment by uri** [comment]
It's not referencing the `assets/images` directory it's referencing a `assets/images/images` directory. But changing it to `(<%= image_path "images/bg-editor-bbcode.png" %>)` might make sense.

**Comment by antage** [comment]
Another reason for `image_path` is moving all images in a separate namespace (for example `markitup/bg-editor-bbcode.png`). Filenames in `images/*` may conflict with other gems or application assets.
