### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by FoboCasteR** [phlipper/markitup-rails#12]
Started work on it
https://github.com/FoboCasteR/markitup-rails/compare/6329d08...rails4

**Comment by gaganawhad** [comment]
@FoboCasteR Thanks!

@phlipper Thanks for maintaining this gem.  Does the latest version of the gem support rails 4? Anything that we can do to help?

**Comment by benhill** [comment]
I could very well be doing something wrong here, but image assets don't seem to load for markitup in a production heroku environment under Rails4. Everything else loads fine, I just get console errors like:

https://<url>/assets/markitup/sets/textile/h1-c1f6d53165241214cf20ca3f0a401d6b.png 404 (Not Found)

**Comment by pedromtavares** [comment]
That's what @FoboCasteR did I believe, any chance of it getting merged into master?
