### ISSUE TITLE
The preview is not displaying

### ISSUE THREAD

**Issue by tispratik** [phlipper/markitup-rails#2]
Thanks for making the gem. I could not get the preview working. Do i need to pass anything else to the settings?

**Comment by tamaloa** [comment]
I had to add the correct path for the preview endpoint mounted by the engine.
The default settings under vendor/assets/javascripts/sets/\* do not all contain the correct path. I only found the markdown setting work out of the box.

Using textile in my case my application.css.scss contains the following:

``` javascript
mySettings.previewParserPath = '/markitup/preview'

$(document).ready(function() {
    $("textarea").markItUp(mySettings)
});
```
