### ISSUE TITLE
Markitup not working. JS errors.

### ISSUE THREAD

**Issue by sugresmax** [phlipper/markitup-rails#6]
Hello.
i'm using markitup-rails (1.0.1) with forem. Text do not formatting.
In browser console i see this errors:
![markitup](https://f.cloud.github.com/assets/3594529/157117/1c5c1e3a-76b6-11e2-82ad-71bfa70616bf.png)

**Comment by uri** [comment]
I will look into this

**Comment by sigmike** [comment]
Until this is fixed you can use [jquery-migrate](https://github.com/jquery/jquery-migrate/). See http://stackoverflow.com/questions/14379681/jquery-quicksand-plugin-uncaught-typeerror-cannot-read-property-msie-of-undef

**Comment by sugresmax** [comment]
Thanks. Your advice helps
